[server]
# Only advertise on the host network interface — leave HA's avahi alone
# The container uses host_network so this is the real NIC (eth0 typically)
use-ipv4=yes
use-ipv6=no
allow-interfaces=enu1
deny-interfaces=lo
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-hinfo=no
publish-workstation=no
disable-publishing=no

[reflector]
enable-reflector=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=768
rlimit-stack=4194304
rlimit-nproc=3
